---
services: docker

env:
  - distro: centos7
  - distro: centos6
  - distro: fedora24
  - distro: ubuntu1604
  - distro: ubuntu1404
  - distro: ubuntu1204
  - distro: debian8

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Run tests.
  - ${PWD}/tests/test.sh

  # Ensure AWS CLI is installed.
  - 'docker exec --tty ${container_id} env TERM=xterm which aws'
