---
- name: Install Python pip
  become: yes
  apt:
    name: python-pip
    state: present

- name: Install AWS CLI
  become: yes
  pip:
    name: awscli

- name: Verify AWS CLI directory is present
  file:
    dest: "~/.aws/"
    state: directory

- name: Apply AWS CLI credentials
  template:
    src: credentials.j2
    dest: ~/.aws/credentials
    mode: 0600

- name: Use AWS CLI configuration
  template:
    src: config.j2
    dest: ~/.aws/config
    mode: 0600
